# Generated by Django 5.1.15 on 2026-07-21 06:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=255)),
                ('original', models.CharField(max_length=512)),
                ('result', models.CharField(max_length=512)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('status', models.CharField(default='done', max_length=16)),
                ('infer_ms', models.FloatField(default=0.0)),
                ('summary', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('x1', models.FloatField()),
                ('y1', models.FloatField()),
                ('x2', models.FloatField()),
                ('y2', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='history.detectionimage')),
            ],
            options={
                'ordering': ['-confidence'],
            },
        ),
        migrations.CreateModel(
            name='DetectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('single', '单图'), ('batch', '批量')], default='single', max_length=16)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '检测中'), ('done', '完成'), ('failed', '失败'), ('canceled', '已取消')], default='done', max_length=16)),
                ('model', models.CharField(max_length=255)),
                ('params', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('image_count', models.IntegerField(default=0)),
                ('done_count', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=64, null=True)),
                ('has_report', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='history_det_created_5dc2a7_idx'), models.Index(fields=['type'], name='history_det_type_0ea53d_idx'), models.Index(fields=['status'], name='history_det_status_47ab43_idx'), models.Index(fields=['model'], name='history_det_model_2343f1_idx')],
            },
        ),
        migrations.AddField(
            model_name='detectionimage',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='history.detectionjob'),
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=32)),
                ('llm_model', models.CharField(max_length=64)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='history.detectionjob')),
            ],
        ),
    ]
